### ISSUE TITLE
Create a minimal Python SDK metrics library

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-python#2330]
As part of our custom metrics projects we want a minimal library for metrics emissions that sits side by side sentry's production deployment. It needs to support enough functionality to be useful as a target for sentry's internal `sentry.metrics` backend.

```[tasklist]
### Tasks
- [x] Implement `metrics.timing`
- [x] implement `metrics.counter`
- [ ] https://github.com/getsentry/sentry/issues/55645
- [x] local lossless aggregation into 10 second buckets
- [ ] https://github.com/getsentry/sentry/issues/55639
```

**Comment by mitsuhiko** [comment]
There is no minimetrics yet, but this is a early draft: https://gist.github.com/mitsuhiko/fe4669d67dc9070aefed100b2928b405
