### ISSUE TITLE
[Milestone] Metrics SDK

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-python#2373]
The goal is to expose the custom metrics functionality in the Python SDK. As this functionality is internal only for dogfooding, it needs to be sufficiently hidden from end users for now.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-python/issues/2374
- [ ] https://github.com/getsentry/sentry/issues/55645
- [x] Switch sentry to internal preview/git release of metrics enabled sentry-python
- [ ] https://github.com/getsentry/sentry-python/issues/2380
```

**Comment by mitsuhiko** [comment]
Mostly tracked in https://github.com/getsentry/sentry-python/issues/2373

**Comment by mitsuhiko** [comment]
This is now resolved. Followup items will be tracked separately.
