### ISSUE TITLE
[2.0] Update cloud computing integrations to use new scopes

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2814]
### Problem Statement

Some integrations are still using old APIs like hub cloning.

### Solution Brainstorm

Update the following integrations from old-style (e.g. configure_scope) hubs&scopes API to the new scopes API.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-python/pull/2882
- [ ] https://github.com/getsentry/sentry-python/pull/2883
- [x] cloud_resource_context (nothing to do)
- [ ] https://github.com/getsentry/sentry-python/pull/2884
```
