### ISSUE TITLE
[2.0] Update DB integrations to use new scopes

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2815]
### Problem Statement

Some integrations are still using old APIs like hub cloning.

### Solution Brainstorm

Update the following integrations from old-style (e.g. `configure_scope`) hubs&scopes API to the new scopes API.

```[tasklist]
### Tasks
- [x] asyncpg https://github.com/getsentry/sentry-python/pull/2845
- [x] clickhouse_driver https://github.com/getsentry/sentry-python/pull/2862
- [x] pymongo https://github.com/getsentry/sentry-python/pull/2862
- [x] redis https://github.com/getsentry/sentry-python/pull/2854
- [x] rediscluster https://github.com/getsentry/sentry-python/pull/2854
- [x] sqlalchemy https://github.com/getsentry/sentry-python/pull/2845
```
