### ISSUE TITLE
Queue instrumentation enhancements: Celery integration

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-python#2959]
Implement the enhancements described in #2951 for the Celery integration

```[tasklist]
### Tasks
- [ ] #2971
- [ ] https://github.com/getsentry/sentry-python/issues/2972
- [ ] https://github.com/getsentry/sentry-python/issues/2974
- [ ] https://github.com/getsentry/sentry-python/issues/2961
- [ ] #3024
- [x] success/failure status - already there
- [x] ~host (`server.address`) - (can be found in `args` of existing `_wrap_tracer`, the attached PR)~ not required per https://develop-git-queue-module.sentry.dev/sdk/performance/modules/queue/
- [ ] https://github.com/getsentry/sentry-python/issues/3078
```

**Comment by szokeasaurusrex** [comment]
All subtasks completed, closing!
