### ISSUE TITLE
Run Tests for integrations in POTel

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#3621]
Run our test suites of the different integrations with the `potel-base` branch. (Just ran `tox -f aiohttp` for example on the `potel-base` branch and made notes on the errors that occured)

- If the integration is checked `[X]` then all tests are green.
- `XXX` means test suite is failing
- `???` means are not run by tests for integrations (so no entry in tox.ini)

There is [this PR](https://github.com/getsentry/sentry-python/pull/3744) that is configured to run all the test suites (and not break on the first failing test suite) where you can see the current state of affairs:

### AI:
- [X] anthropic
- [X] cohere
- [X] langchain
- [X] openai
- [X] huggingface_hub

### AWS:
- [X] aws_lambda

### Cloud:
- [X] boto3
- [X] chalice
- [X] cloud_resource_context 
- [X] gcp 

### Common:
- [X] common

### DBs:
- [X] asyncpg
- [X] clickhouse_driver
- [X] pymongo 
- [X] redis 
- [X] redis_py_cluster_legacy
- [X] sqlalchemy (1 test failing, because we do not enforce the 1000 spans per transaction limit)

### GraphQL:
- [X] ariadne
- [X] gql 
- [X] graphene
- [X] strawberry

### Misc:
- [X] launchdarkly
- [X] loguru
- [X] openfeature
- [X] opentelemetry
- [X] potel
- [X] pure_eval
- [X] trytond

### Network:
- [X] gevent
- [X] grpc (tests crash!, to many events)
- [X] httpx (`'POTelSpan' object has no attribute '_span_recorder'`, wrong bread crumbs)
- [X] requests

### Tasks:
- [X] arq 
- [X] beam
- [X] celery (Tests fail because of some import errors)
- [X] dramatiq
- [X] huey
- [X] ray
- [X] rq 
- [X] spark

### Web 1:
- [x] django 
- [x] flask
- [x] starlette
- [x] fastapi

### Web 2:
- [X] aiohttp
- [X] asgi
- [X] bottle
- [X] falcon
- [X] litestar
- [X] pyramid
- [X] quart
- [X] sanic
- [X] starlite
- [X] tornado

**Comment by antonpirker** [comment]
All tests are green now, so we can close this tracking issue.
